import React from 'react';

import './game.css';

export function Board() {
    return (
        <div className="column text-center">
            <table id="board">
                <tr>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>D</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>O</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>G</div>
                    </td>
                    <td>
                        <div>A</div>
                    </td>
                    <td>
                        <div>M</div>
                    </td>
                    <td>
                        <div>E</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                    <td>
                        <div>I</div>
                    </td>
                </tr>
            </table>        
        </div>
    );
}